default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  
development:
  <<: *default
  host: localhost
  database: toodles_dev
  username:
  password:

test:
  <<: *default
  database: toodles_test
  username:
  password:

production:
  <<: *default
  database: toodles_prod
  username:
  password:
