# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d992d9a417dda3f26155063a2eb336f9d58aa692b52e9ea6c9f167fb8ba7a99907734fce7e3b926163e9e2fe2e64ac6883ac6513f47e2450a2fd21a6b458d7fc
  gmail_username: toodlesapp@gmail.com
  gmail_password: toodlespassword

test:
  secret_key_base: 4b684226c2ce07b32fcaa8a7b7647e50fc1f1759864f625581987b7fc15ac4d9d9d700d59ad5794f7ebb591ca2593233050759105302b7d590efcc8d2bbcd191
  gmail_username: toodlesapp@gmail.com
  gmail_password: toodlespassword

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  gmail_username: toodlesapp@gmail.com
  gmail_password: toodlespassword
